Pablo development
matty377/summer22-sps-14 pull request #23
Opened 2022-07-14 02:46 UTC by pablo-ramm

Add style to the new restaurant form.

2022-07-15 23:01 UTC, trucdg requested changes
I'm not sure why when I try to add a new restaurant, it gives me an error 
![image](https://user-images.githubusercontent.com/91285203/179322366-dd3ba86b-e639-4c4c-aa85-e85271ea5055.png)

2022-07-15 23:01 UTC, trucdg commented on group-project/src/main/webapp/index.html
> +        <button href="/newRestaurant.html" class="btn" style="background-color: #1F1D2B; border-color: #EA7C69; color: #EA7C69;"><a style="color: #EA7C69;" href="/newRestaurant.html">add restaurant</
I think it'll look better if the inner text of the button is all uppercase. Also, can you center align the button. I think you can add a Class to your button and my WTE button, then change the element selector in the CSS file to be the class. This way, 2 buttons can have the same design 🤔 
![image](https://user-images.githubusercontent.com/91285203/179322155-dd83403e-82f2-4f5e-aa4b-e34508344517.png)

2022-07-15 23:05 UTC, trucdg commented on group-project/src/main/webapp/index.html
> +        <button href="/newRestaurant.html" class="btn" style="background-color: #1F1D2B; border-color: #EA7C69; color: #EA7C69;"><a style="color: #EA7C69;" href="/newRestaurant.html">add restaurant</
Also, nit: commit message is preferably be in present tense I believe. (since it summarizes what a change _does_

2022-07-17 00:25 UTC, mybffjustin requested changes, later dismissed
You might want to consider untracking the target directory

2022-07-17 18:20 UTC, pablo-ramm commented on group-project/src/main/webapp/index.html
> +        <button href="/newRestaurant.html" class="btn" style="background-color: #1F1D2B; border-color: #EA7C69; color: #EA7C69;"><a style="color: #EA7C69;" href="/newRestaurant.html">add restaurant</
I think the error its because you need to run  `gcloud config set project summer22-sps-14` first

2022-07-20 17:46 UTC, trucdg approved these changes

2022-07-20 17:47 UTC, merged